/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jtodo.kotlin-library-conventions")
}

dependencies {
    implementation("org.postgresql:postgresql")
    implementation("org.jdbi:jdbi")
}
